on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

jobs:
  build-and-test-app:
    name: Build and Test Flipper App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.target }}
    steps:
    - uses: actions/checkout@v3
    - name: Get Deps
      run: git submodule update --init --recursive
    - name: Setup Toolchain
      run: rustup component add llvm-tools
    - run: sudo apt install libudev-dev
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --release --verbose
